import { defineSiteConfig } from '@stacksjs/stx'

const en = {
  'nav.home': 'Home',
  'nav.about': 'About',
  'nav.races': 'Races',
  'nav.coaching': 'Coaching',
  'home.kicker': 'Ultra Runner · Coach · Husband',
  'home.lede': 'Finisher of SwissPeaks 700K, Lappland Arctic Ultra 500K, and the world\'s most demanding mountain races. Pushing limits where the trail ends and willpower begins.',
  'home.stats.longest': 'Longest Race',
  'home.stats.lappland': 'Lappland 500K',
  'home.stats.arctic': 'Arctic Finish',
  'home.featured.kicker': 'Latest Achievement',
  'home.featured.body': '515 km through the frozen wilderness of Swedish Lapland. Temperatures dropping well below -30°C, pulling a sled through snow and ice for nearly seven days straight. Silver medal finish.',
  'home.featured.distance': 'Distance',
  'home.featured.time': 'Finish Time',
  'home.featured.overall': 'Overall',
  'home.upcoming': 'Upcoming',
  'home.upcomingSub': '400 km across the Swiss Alps — the next chapter',
  'home.followCta': 'Follow the Journey →',
  'home.section.about.body': 'From first ultra to 700K finisher. The story, the philosophy, and the partnerships that fuel the journey.',
  'home.section.about.cta': 'Learn More →',
  'home.section.races.body': 'Full UTMB-indexed results. From Chiemgauer 100 to SwissPeaks 700K — every start line, every finish.',
  'home.section.races.cta': 'View Results →',
  'home.section.coaching.body': '1:1 coaching built on real experience. Personalized plans for athletes ready to go further.',
  'home.section.coaching.cta': 'Get Started →',
  'footer.coaching': 'Coaching',
}

export const site = defineSiteConfig({
  name: 'Paweł Dregan',
  url: 'https://paweldregan.com',
  description: 'Ultra runner. Coach. Husband. Finisher of SwissPeaks 700K, Lappland Arctic Ultra 500K, and the world\'s most demanding mountain races.',
  social: {
    instagram: 'ultrarunnerpaw',
    youtube: 'UC3BxCTwxiIROpXagOexE9gw',
  },
  seo: {
    siteName: 'Paweł Dregan',
    twitter: 'ultrarunnerpaw',
    locale: 'en_US',
    type: 'website',
    favicon: '/favicon.svg',
  },
  i18n: {
    locales: ['en', 'de', 'pl'],
    defaultLocale: 'en',
    labels: { en: 'EN', de: 'DE', pl: 'PL' },
    translations: {
      en,
      de: {
        'nav.home': 'Start',
        'nav.about': 'Über mich',
        'nav.races': 'Rennen',
        'nav.coaching': 'Coaching',
        'home.kicker': 'Ultraläufer · Coach · Ehemann',
        'home.lede': 'Finisher von SwissPeaks 700K, Lappland Arctic Ultra 500K und den anspruchsvollsten Bergrennen der Welt. Grenzen verschieben, wo der Weg endet und der Wille beginnt.',
        'home.stats.longest': 'Längstes Rennen',
        'home.stats.lappland': 'Lappland 500K',
        'home.stats.arctic': 'Arktischer Zieleinlauf',
        'home.featured.kicker': 'Neueste Leistung',
        'home.featured.body': '515 km durch die gefrorene Wildnis Schwedisch-Lapplands. Temperaturen weit unter -30 °C, einen Schlitten fast sieben Tage lang durch Schnee und Eis ziehend. Silbermedaille im Ziel.',
        'home.featured.distance': 'Distanz',
        'home.featured.time': 'Zielzeit',
        'home.featured.overall': 'Gesamt',
        'home.upcoming': 'Kommend',
        'home.upcomingSub': '400 km quer durch die Schweizer Alpen — das nächste Kapitel',
        'home.followCta': 'Reise verfolgen →',
        'home.section.about.body': 'Vom ersten Ultra zum 700K-Finisher. Die Geschichte, die Philosophie und die Partnerschaften hinter dem Weg.',
        'home.section.about.cta': 'Mehr erfahren →',
        'home.section.races.body': 'UTMB-indexierte Ergebnisse. Vom Chiemgauer 100 bis zum SwissPeaks 700K — jede Startlinie, jedes Ziel.',
        'home.section.races.cta': 'Ergebnisse ansehen →',
        'home.section.coaching.body': '1:1-Coaching aus echter Erfahrung. Individuelle Pläne für Athleten, die weiter gehen wollen.',
        'home.section.coaching.cta': 'Loslegen →',
        'footer.coaching': 'Coaching',
      },
      pl: {
        'nav.home': 'Strona główna',
        'nav.about': 'O mnie',
        'nav.races': 'Wyścigi',
        'nav.coaching': 'Coaching',
        'home.kicker': 'Ultramaratończyk · Trener · Mąż',
        'home.lede': 'Finisher SwissPeaks 700K, Lappland Arctic Ultra 500K i najbardziej wymagających biegów górskich na świecie. Przesuwam granice tam, gdzie kończy się szlak, a zaczyna wola.',
        'home.stats.longest': 'Najdłuższy bieg',
        'home.stats.lappland': 'Lappland 500K',
        'home.stats.arctic': 'Meta arktyczna',
        'home.featured.kicker': 'Ostatnie osiągnięcie',
        'home.featured.body': '515 km przez zamarzniętą dzicz szwedzkiej Laponii. Temperatury grubo poniżej -30°C, sanki ciągnięte przez śnieg i lód przez prawie siedem dni. Srebrny medal na mecie.',
        'home.featured.distance': 'Dystans',
        'home.featured.time': 'Czas mety',
        'home.featured.overall': 'Klasyfikacja',
        'home.upcoming': 'Najbliższe',
        'home.upcomingSub': '400 km przez Alpy Szwajcarskie — kolejny rozdział',
        'home.followCta': 'Śledź podróż →',
        'home.section.about.body': 'Od pierwszego ultra do finishera 700K. Historia, filozofia i partnerstwa, które napędzają drogę.',
        'home.section.about.cta': 'Dowiedz się więcej →',
        'home.section.races.body': 'Wyniki indeksowane przez UTMB. Od Chiemgauer 100 po SwissPeaks 700K — każda linia startu, każda meta.',
        'home.section.races.cta': 'Zobacz wyniki →',
        'home.section.coaching.body': 'Coaching 1:1 oparty na realnym doświadczeniu. Plany indywidualne dla zawodników, którzy chcą iść dalej.',
        'home.section.coaching.cta': 'Zacznij →',
        'footer.coaching': 'Coaching',
      },
    },
  },
  pages: {
    '/': {
      title: 'Paweł Dregan — Ultra Runner',
      description: 'Finisher of SwissPeaks 700K, Lappland Arctic Ultra 500K, and the world\'s most demanding mountain races. Pushing limits where the trail ends and willpower begins.',
      priority: 1.0,
      changefreq: 'weekly',
    },
    '/about': {
      title: 'About — Paweł Dregan',
      description: 'From first ultra to 700K finisher. The story, the philosophy, and the partnerships behind the journey.',
      priority: 0.9,
    },
    '/races': {
      title: 'Races — Paweł Dregan',
      description: 'UTMB-indexed race results from 100K to 700K. Every start line, every finish, every lesson.',
      priority: 0.9,
    },
    '/coaching': {
      title: 'Coaching — Paweł Dregan',
      description: 'Personalized 1:1 ultra running coaching built on real experience. From your first 50K to your biggest dream race.',
      priority: 0.9,
      changefreq: 'monthly',
    },
  },
})
